on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: ci

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: camshaft/install@v1
        with:
          crate: marathon

      - name: Run marathon check
        run: marathon check
